# Generated by Django 4.1.5 on 2023-02-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
