# Generated by Django 4.1.5 on 2023-02-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_message_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение пользователя', 'verbose_name_plural': 'Сообщения пользователей'},
        ),
    ]
